spring.application.name=sdts-backend
spring.datasource.url=jdbc:mysql://localhost:3306/smart_deadline_tracking_system
spring.datasource.username=root
spring.datasource.password=AD_0226

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dharsanadurai3@gmail.com
spring.mail.password=qder giwj vblc qcax

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true